version: '3.4'

services:
  dapr.publishapi:
    container_name: dapr.publishapi
    image: dapr/publish.api
    build:
      context: .
      dockerfile: server/Dapr.PublishApi/Dockerfile
    depends_on:
      - rabbitmq
      - redis
  
  dapr.publishapi.dapr:
    container_name: dapr.publishapi.dapr
    image: "daprio/daprd:1.7.3"
    network_mode: "service:dapr.publishapi"
    depends_on:
      - dapr.publishapi

  dapr.subscribeapi:
    container_name: dapr.subscribeapi
    image: dapr/subscribe.api
    build:
      context: .
      dockerfile: server/Dapr.SubscribeApi/Dockerfile
    depends_on:
      - rabbitmq
      - redis

  dapr.subscribeapi.dapr:
    container_name: dapr.subscribeapi.dapr
    image: "daprio/daprd:1.7.3"
    network_mode: "service:dapr.subscribeapi"
    depends_on:
      - dapr.subscribeapi

  #Pub-Sub
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management

  #State
  redis:
    container_name: redis
    image: redis:alpine