version: '3.4'

services:
  dapr.publishapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
  
  dapr.publishapi.dapr:
    command: ["./daprd",
      "-app-id", "dapr.publishapi",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configurations/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configurations/:/configurations"
  
  dapr.subscribeapi.dapr:
    command: ["./daprd",
      "-app-id", "dapr.subscribeapi",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configurations/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configurations/:/configurations"
  
  dapr.othersubscribeapi.dapr:
    command: ["./daprd",
      "-app-id", "dapr.othersubscribeapi",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configurations/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configurations/:/configurations"
  
  dapr.subscribeyamlapi.dapr:
    command: ["./daprd",
      "-app-id", "dapr.subscribeyamlapi",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configurations/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configurations/:/configurations"
  
  dapr.othersubscribebyyamlapi.dapr:
    command: ["./daprd",
      "-app-id", "dapr.othersubscribebyyamlapi",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configurations/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configurations/:/configurations"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"