version: '3.4'

services:
  dapr.publishapi:
    #image: ${DOCKER_REGISTRY-}daprpublishapi
    image: dapr/publishapi
    build:
      context: .
      dockerfile: server/Dapr.PublishApi/Dockerfile
    depends_on:
      - rabbitmq

  dapr.publishapi.dapr:
    container_name: dapr.publishapi
    image: "daprio/daprd:1.2.0"
    network_mode: "service:dapr.publishapi"
    depends_on:
      - dapr.publishapi

  dapr.subscribeapi:
    #image: ${DOCKER_REGISTRY-}daprsubscribeapi
    image: dapr/subscribeapi
    build:
      context: .
      dockerfile: server/Dapr.SubscribeApi/Dockerfile
    depends_on:
      - rabbitmq

  dapr.subscribeapi.dapr:
    container_name: dapr.subscribeapi
    image: "daprio/daprd:1.2.0"
    network_mode: "service:dapr.subscribeapi"
    depends_on:
      - dapr.subscribeapi

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine